services:
  - type: web
    name: personal-rag
    env: docker
    envVars:
      - key: ENV
        value: production
    plan: free
    region: oregon
    disk:
      - name: chroma-db
        mountPath: /chroma-db
        sizeGB: 1
      - name: rag-docs
        mountPath: /rag-docs
        sizeGB: 1
    autoDeploy: false
    healthCheckPath: /docs